[tool.ruff]
line-length = 150
target-version = "py311"

[tool.ruff.lint]
# Mandated rule sets from Phase 1
select = ["E", "F", "B", "I"] # Error, Flake, Bugbear, Isort
ignore = ["B008", "E501", "E701", "B904", "B023", "E722"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"app/main.py" = ["E402"]
